apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "botforge.fullname" . }}-uploads
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
