apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botforge.fullname" . }}-keys
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  public.pem: {{ .Values.backend.keys.publicKey | quote }}
  private.pem: {{ .Values.backend.keys.privateKey | quote }}
