apiVersion: v1
kind: Service
metadata:
  name: {{ include "botforge.fullname" . }}-backend
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.backend.service.type "NodePort" }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "botforge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: backend
