apiVersion: v1
kind: Service
metadata:
  name: {{ include "botforge.fullname" . }}-redis
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "botforge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: redis
