apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "botforge.fullname" . }}-postgres
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "botforge.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "botforge.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "botforge.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: postgres
    spec:
      initContainers:
        - name: fix-ssl-permissions
          image: "{{ .Values.postgres.image }}"
          command:
            - sh
            - -c
            - |
              cp /tmp/ssl-source/* /tmp/ssl-target/
              chown 999:999 /tmp/ssl-target/*
              chmod 600 /tmp/ssl-target/server.key
              chmod 644 /tmp/ssl-target/server.crt
          volumeMounts:
            - name: ssl-certs-source
              mountPath: /tmp/ssl-source
              readOnly: true
            - name: ssl-certs
              mountPath: /tmp/ssl-target
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "botforge.fullname" . }}-secrets
                  key: postgres-password
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.env.POSTGRES_DB }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.env.POSTGRES_USER }}"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          args:
            - -c
            - ssl=on
            - -c
            - ssl_cert_file=/var/lib/postgresql/ssl/server.crt
            - -c
            - ssl_key_file=/var/lib/postgresql/ssl/server.key
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/create.sql
              subPath: create.sql
            - name: ssl-certs
              mountPath: /var/lib/postgresql/ssl
              readOnly: true
      volumes:
        - name: initdb
          configMap:
            name: {{ include "botforge.fullname" . }}-initdb
        - name: ssl-certs-source
          secret:
            secretName: {{ include "botforge.fullname" . }}-postgres-ssl
            defaultMode: 0600
        - name: ssl-certs
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.postgres.persistence.storageClass }}
        storageClassName: {{ .Values.postgres.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
