{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "botforge.fullname" . }}-mongo
  labels:
    {{- include "botforge.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "botforge.fullname" . }}-mongo
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "botforge.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: mongo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "botforge.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.mongo.image }}"
          ports:
            - name: mongo
              containerPort: {{ .Values.mongo.service.port }}
              protocol: TCP
          env:
            {{- range $key, $val := .Values.mongo.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.mongo.persistence.storageClass }}
        storageClassName: {{ .Values.mongo.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongo.persistence.size }}
{{- end }}
